name: Fix Home URL

on:
  # Allow manual trigger from Actions tab
  workflow_dispatch:
  
  # Run when pushed to master branch
  push:
    branches:
      - master
    paths:
      - 'index.html'  # Only run when index.html changes

# Permissions for this workflow
permissions:
  contents: write  # Allow reading and writing to repository

jobs:
  fix-home-url:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history for merging
      
      - name: Pull latest changes
        run: git pull --rebase origin master
      
      - name: Fix Home button URL
        run: |
          if grep -q '<a href="/"' index.html; then
            echo "Fixing home button URL for GitHub Pages..."
            sed -i 's#<a href="/"#<a href="./"#' index.html
          else
            echo "Home button URL is already correct."
          fi
          
      - name: Check for changes
        id: git-check
        run: |
          git add index.html
          git status
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Configure Git
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git add index.html
          git commit -m "fix: Update home button URL for GitHub Pages"
          
      - name: Push changes
        if: steps.git-check.outputs.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: false 