name: Format Code

on:
  # Run when pushed to master branch or pull requests
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

  # Allow manual trigger from Actions tab
  workflow_dispatch:

# Permissions for this workflow
permissions:
  contents: write  # Allow reading and writing to repository

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Prettier
        run: npm install --save-dev prettier

      - name: Create Prettier config
        run: |
          cat > .prettierrc << EOF
          {
            "singleQuote": true,
            "trailingComma": "all",
            "tabWidth": 4,
            "useTabs": true,
            "semi": true,
            "printWidth": 10000,
            "bracketSpacing": true,
            "arrowParens": "always",
            "endOfLine": "lf",
            "bracketSameLine": false,
            "htmlWhitespaceSensitivity": "css",
            "jsxSingleQuote": false
          }
          EOF

      - name: Format code with Prettier
        run: npx prettier --write "**/*.{js,jsx,ts,tsx,json,css,html,md}"

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Configure Git
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true' && github.event_name != 'pull_request'
        run: |
          git add -A
          git commit -m "style: Format code with Prettier"

      - name: Push changes
        if: steps.git-check.outputs.changes == 'true' && github.event_name != 'pull_request'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: false 